# Generated by Django 5.2 on 2025-04-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahp_rank', models.FloatField()),
                ('final_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nb_places', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('requirements', models.TextField()),
                ('skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit_flexibility', models.BooleanField(default=False, help_text='Ability to work in different business units')),
                ('past_experience_required', models.BooleanField(default=False)),
                ('min_education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('foreign_language_required', models.BooleanField(default=False)),
                ('strategic_thinking_required', models.BooleanField(default=False)),
                ('oral_communication_required', models.BooleanField(default=False)),
                ('computer_skills_required', models.BooleanField(default=False)),
            ],
        ),
    ]
