# Generated by Django 5.2 on 2025-04-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteria',
            field=models.CharField(max_length=255),
        ),
    ]
