# Generated by Django 5.2 on 2025-04-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_criteria_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHPPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_data', models.JSONField(help_text='The pairwise comparison matrix')),
                ('criteria_keys', models.JSONField(help_text='List of criteria keys used in the matrix')),
                ('criteria_names', models.JSONField(help_text='List of criteria names shown to user')),
                ('weights', models.JSONField(help_text='The calculated priority weights for each criterion')),
                ('consistency_ratio', models.FloatField(help_text='Consistency ratio of the matrix')),
                ('is_consistent', models.BooleanField(default=False, help_text='Whether the matrix is consistent (CR < 0.1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ahp_priority', to='jobs.job')),
            ],
        ),
    ]
