# Generated by Django 5.2 on 2025-04-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_remote_work_job_years_experience_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='min_education_level',
            field=models.CharField(choices=[('none', 'No formal education required'), ('high_school', 'High School Diploma'), ('certificate', 'Professional Certificate'), ('associates', "Associate's Degree"), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate/PhD'), ('professional', 'Professional Degree (MD, JD, etc.)')], default='none', help_text='Minimum required education level', max_length=100),
        ),
    ]
