# Generated by Django 5.2 on 2025-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_min_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedata',
            name='is_penalize',
            field=models.BooleanField(default=False, help_text='Indicates if the candidate is penalized for duplicate applications'),
        ),
    ]
