"""new  migration

Revision ID: 19ac449bf2dd
Revises: 5f5b4c503905
Create Date: 2025-04-12 00:24:04.382995

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19ac449bf2dd"
down_revision: Union[str, None] = "5f5b4c503905"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email", table_name="users")
    # op.drop_table('users')
    op.drop_index("ix_jobs_company", table_name="jobs")
    op.drop_index("ix_jobs_deadline", table_name="jobs")
    op.drop_index("ix_jobs_description", table_name="jobs")
    op.drop_index("ix_jobs_experience", table_name="jobs")
    op.drop_index("ix_jobs_id", table_name="jobs")
    op.drop_index("ix_jobs_location", table_name="jobs")
    op.drop_index("ix_jobs_requirements", table_name="jobs")
    op.drop_index("ix_jobs_salary", table_name="jobs")
    op.drop_index("ix_jobs_skills", table_name="jobs")
    op.drop_index("ix_jobs_title", table_name="jobs")
    op.drop_index("ix_jobs_type", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("employers")
    op.drop_index("ix_candidates_id", table_name="candidates")
    op.drop_index("ix_candidates_name", table_name="candidates")
    op.drop_table("candidates")
    op.drop_index("ix_criteria_id", table_name="criteria")
    op.drop_index("ix_criteria_name", table_name="criteria")
    op.drop_table("criteria")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "criteria",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="criteria_pkey"),
    )
    op.create_index("ix_criteria_name", "criteria", ["name"], unique=False)
    op.create_index("ix_criteria_id", "criteria", ["id"], unique=False)
    op.create_table(
        "candidates",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("ahp_rank", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "final_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["id"], ["users.id"], name="candidates_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="candidates_pkey"),
    )
    op.create_index("ix_candidates_name", "candidates", ["name"], unique=False)
    op.create_index("ix_candidates_id", "candidates", ["id"], unique=False)
    op.create_table(
        "employers",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["id"], ["users.id"], name="employers_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="employers_pkey"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("nb_places", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("experience", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("salary", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("deadline", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("requirements", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("skills", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="jobs_pkey"),
    )
    op.create_index("ix_jobs_type", "jobs", ["type"], unique=False)
    op.create_index("ix_jobs_title", "jobs", ["title"], unique=False)
    op.create_index("ix_jobs_skills", "jobs", ["skills"], unique=False)
    op.create_index("ix_jobs_salary", "jobs", ["salary"], unique=False)
    op.create_index("ix_jobs_requirements", "jobs", ["requirements"], unique=False)
    op.create_index("ix_jobs_location", "jobs", ["location"], unique=False)
    op.create_index("ix_jobs_id", "jobs", ["id"], unique=False)
    op.create_index("ix_jobs_experience", "jobs", ["experience"], unique=False)
    op.create_index("ix_jobs_description", "jobs", ["description"], unique=False)
    op.create_index("ix_jobs_deadline", "jobs", ["deadline"], unique=False)
    op.create_index("ix_jobs_company", "jobs", ["company"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "password_hash", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    # ### end Alembic commands ###
