# Generated by Django 5.2 on 2025-04-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.jobseeker'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'jobseeker')},
        ),
    ]
